//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        public int A_id { get; set; }
        public string A_style { get; set; }
        public System.DateTime A_date { get; set; }
        public string A_status { get; set; }
        public int O_id { get; set; }
    
        public virtual APic APic { get; set; }
        public virtual Juxtapose Juxtapose { get; set; }
        public virtual Oldman_Data Oldman_Data { get; set; }
    }
}
