//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulation
    {
        public int C_id { get; set; }
        public string C_name { get; set; }
        public string C_address { get; set; }
        public string C_date { get; set; }
        public string C_phone { get; set; }
        public int C_number { get; set; }
        public string C_time { get; set; }
        public int O_id { get; set; }
    
        public virtual Oldman_Data Oldman_Data { get; set; }
    }
}
