//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Guardian_AngelEntities : DbContext
    {
        public Guardian_AngelEntities()
            : base("name=Guardian_AngelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accident { get; set; }
        public virtual DbSet<APic> APic { get; set; }
        public virtual DbSet<Consulation> Consulation { get; set; }
        public virtual DbSet<Emergency_Contact> Emergency_Contact { get; set; }
        public virtual DbSet<GPS> GPS { get; set; }
        public virtual DbSet<Juxtapose> Juxtapose { get; set; }
        public virtual DbSet<Manage_Account> Manage_Account { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<NPGrouping> NPGrouping { get; set; }
        public virtual DbSet<Oldman_Data> Oldman_Data { get; set; }
        public virtual DbSet<Pill> Pill { get; set; }
        public virtual DbSet<Pill_Factory_Category> Pill_Factory_Category { get; set; }
        public virtual DbSet<Relationship> Relationship { get; set; }
        public virtual DbSet<Security> Security { get; set; }
        public virtual DbSet<Time> Time { get; set; }
        public virtual DbSet<User_Data> User_Data { get; set; }
    }
}
