//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notice()
        {
            this.NPGrouping = new HashSet<NPGrouping>();
            this.Time = new HashSet<Time>();
        }
    
        public int N_id { get; set; }
        public string N_name { get; set; }
        public string N_startdate { get; set; }
        public string N_enddate { get; set; }
        public int O_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPGrouping> NPGrouping { get; set; }
        public virtual Oldman_Data Oldman_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Time> Time { get; set; }
    }
}
