//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pill()
        {
            this.NPGrouping = new HashSet<NPGrouping>();
        }
    
        public int P_id { get; set; }
        public string P_name { get; set; }
        public Nullable<int> P_pharmaceutical_factory_Id { get; set; }
        public string P_product_name { get; set; }
        public string P_scientific_name { get; set; }
        public string P_code { get; set; }
        public string P_remark { get; set; }
        public string P_photo { get; set; }
        public string P_create_date { get; set; }
        public string P_update_date { get; set; }
        public string P_editor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPGrouping> NPGrouping { get; set; }
        public virtual Pill_Factory_Category Pill_Factory_Category { get; set; }
    }
}
