//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int GB_id { get; set; }
        public Nullable<int> gbNumber { get; set; }
        public string cenLng { get; set; }
        public string cenLat { get; set; }
        public string neLng { get; set; }
        public string neLat { get; set; }
        public string swLng { get; set; }
        public string swLat { get; set; }
        public Nullable<int> O_id { get; set; }
    
        public virtual Oldman_Data Oldman_Data { get; set; }
    }
}
