//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Data()
        {
            this.Oldman_Data = new HashSet<Oldman_Data>();
        }
    
        public int U_id { get; set; }
        public string U_lname { get; set; }
        public string U_fname { get; set; }
        public string U_password { get; set; }
        public string U_account { get; set; }
        public string U_Phone { get; set; }
        public string U_address { get; set; }
        public string U_organization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oldman_Data> Oldman_Data { get; set; }
    }
}
